
spring:
  profiles:
    active: dev
    
---
spring:
  profiles: dev
server:
  port: 1010
  
---
spring:
  profiles: sit
server:
  port: 2020
  
---
spring:
  profiles:
    default: uat
server:
  port: 3030
  
---
spring:
  profiles: pilot
server:
  port: 4040
    
    
      
